# Generated by Django 5.1.2 on 2024-11-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
